0it [00:00, ?it/s]0it [00:01, ?it/s]
Trying to download Carmilla ... succeeded.
Traceback (most recent call last):
  File "Gutenberg_download.py", line 53, in download_full_texts
    open(out_path + '/' + filename)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/users/kipnisal/Data/G/Gut_0.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Gutenberg_download.py", line 60, in download_full_texts
    text = strip_headers(down_etext(r[1].id)).strip()
NameError: name 'down_etext' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Gutenberg_download.py", line 101, in <module>
    download_full_texts(db, args.o)
  File "Gutenberg_download.py", line 81, in download_full_texts
    data.to_csv(out_path + '/' + filename)
  File "/home/users/kipnisal/CJinstalled/miniconda/lib/python3.7/site-packages/pandas/core/generic.py", line 3402, in to_csv
    storage_options=storage_options,
  File "/home/users/kipnisal/CJinstalled/miniconda/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/home/users/kipnisal/CJinstalled/miniconda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 234, in save
    storage_options=self.storage_options,
  File "/home/users/kipnisal/CJinstalled/miniconda/lib/python3.7/site-packages/pandas/io/common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/users/kipnisal/Data/G/Gut_0.csv'
/var/spool/slurmd/job28031167/slurm_script: line 7: utenberg: command not found
